apiVersion: v1
kind: Pod
metadata:
  labels:
  name: pod1
spec: 
  nodeSelector:
    worker: worker1
  containers:
  - image: ubi8:latest  
    name: pod1
    command:
    - sleep
    - infinity
    volumeMounts:
    - mountPath: /mnt/data
      name: myvolume
  volumes:
  - name: myvolume
    persistentVolumeClaim:
      claimName: pvc1
