apiVersion: v1
kind: Pod
metadata:
  name: pod3
spec: 
  nodeSelector:
    worker: worker3
  containers:
  - image: ubi8:latest 
    name: pod3
    command:
    - sleep
    - infinity
    volumeMounts:
    - mountPath: /mnt/data
      name: myvolume
  volumes:
  - name: myvolume
    persistentVolumeClaim:
      claimName: pvc1
